### ISSUE TITLE
Lag for choosing stuff in menu and in game

### ISSUE THREAD

**Issue by farooqkz** [P1X-in/Tanks-of-Freedom-3-D#13]
Hello. I just tried the Linux version without having a dedicated GPU:

```
CPU(s):                          4
On-line CPU(s) list:             0-3
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
```

And there was lag when hovering on menu items or game squares. Note that my guess is that the problem is not with hardware because I have 4 cores and all of them were not being used at the same time.

**Comment by czlowiekimadlo** [comment]
What is the GPU used here?

**Comment by farooqkz** [comment]
> What is the GPU used here?

iGPU.

**Comment by czlowiekimadlo** [comment]
That might be the issue then. 3D in Godot is quite demanding, integrated GPUs on Intel are just not cutting it. I have already tested the game on these, and there is nothing I can do really. There is an option to set FPS limit to 30 in the game settings, but I doubt it would help much.

**Comment by farooqkz** [comment]
> That might be the issue then. 3D in Godot is quite demanding, integrated GPUs on Intel are just not cutting it. I have already tested the game on these, and there is nothing I can do really. There is an option to set FPS limit to 30 in the game settings, but I doubt it would help much.

hmm but I think the full capability of my HW is not used. I check with top and CPU usage is less than 100% most of the time.

**Comment by czlowiekimadlo** [comment]
That is to be expected, unless it's AI turn, CPU is not supposed to be used that much.

**Comment by farooqkz** [comment]
You were right. iGPU 3D rendering is used to its maximum and there is still lag. Closing this.

**Comment by czlowiekimadlo** [comment]
I have linux laptop with i5-8250U and game is failing completely on it, 3D objects showing up for a moment, and then dissapearing, so there is nothing. Since the game is aimed at Steam Deck and it manages to run on it fine, I think GPU equivalent to that could be considered a minimum requirement.

As far as I was able to find, Deck's GPU is roughly equivalent to Nvidia GTX 1050 or GTX 950 in terms of raw compute power. xx50 class GPUs are usually the lowest tier being put on laptops with dedicated GPUs, so even the cheapest gaming laptops should be able to handle it.
